# Generated by Django 6.0.4 on 2026-04-11 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ml_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('single', '单次预测'), ('batch', '批量筛选')], max_length=10)),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20)),
                ('input_data', models.JSONField()),
                ('result', models.JSONField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'prediction_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinetuneTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20)),
                ('training_file', models.FileField(upload_to='finetune_data/')),
                ('config', models.JSONField(default=dict)),
                ('log', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('base_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ml_models.mlmodel')),
                ('result_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finetune_source', to='ml_models.mlmodel')),
            ],
            options={
                'db_table': 'finetune_tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
