# Generated by Django 6.0.4 on 2026-04-11 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ml_models', '0002_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='finetunetask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finetune_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='predictiontask',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ml_models.mlmodel'),
        ),
        migrations.AddField(
            model_name='predictiontask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
