# Generated by Django 6.0.4 on 2026-04-11 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('model_type', models.CharField(choices=[('pretrained', '预训练模型'), ('finetuned', '微调模型')], max_length=20)),
                ('model_file', models.FileField(upload_to='models/')),
                ('is_large', models.BooleanField(default=True)),
                ('num_classes', models.IntegerField(default=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_models', to='ml_models.mlmodel')),
            ],
            options={
                'db_table': 'ml_models',
                'ordering': ['-created_at'],
            },
        ),
    ]
